//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace offerDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class company
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public company()
        {
            this.contactPersons = new HashSet<contactPerson>();
        }
    
        public int companyId { get; set; }
        public string cname { get; set; }
        public Nullable<byte> rounds { get; set; }
        public Nullable<int> tagId { get; set; }
        public Nullable<System.DateTime> AppliedDate { get; set; }
        public Nullable<System.DateTime> responseDate { get; set; }
        public Nullable<byte> packageMin { get; set; }
        public Nullable<byte> packageMax { get; set; }
        public Nullable<int> locationId { get; set; }
        public string condition { get; set; }
        public string response { get; set; }
        public Nullable<byte> Scheduled { get; set; }
        public Nullable<System.DateTime> interviewDAte { get; set; }
        public Nullable<byte> isActive { get; set; }
        public string website { get; set; }
    
        public virtual location location { get; set; }
        public virtual tag tag { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<contactPerson> contactPersons { get; set; }
    }
}
