//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace offerDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class contactPerson
    {
        public int contactPersonId { get; set; }
        public string contactPersonName { get; set; }
        public Nullable<decimal> contactNumber { get; set; }
        public Nullable<byte> isActive { get; set; }
    }
}
