//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace offerDataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class myofferEntities : DbContext
    {
        public myofferEntities()
            : base("name=myofferEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<company> companies { get; set; }
        public virtual DbSet<contactPerson> contactPersons { get; set; }
        public virtual DbSet<location> locations { get; set; }
        public virtual DbSet<tag> tags { get; set; }
        public virtual DbSet<technology> technologies { get; set; }
    }
}
